package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB340)
val md_theme_dark_onPrimary = Color(0xFF4A2B00)
val md_theme_dark_primaryContainer = Color(0xFF6C4000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCA6)
val md_theme_dark_secondary = Color(0xFFFFB4A0)
val md_theme_dark_onSecondary = Color(0xFF5E1705)
val md_theme_dark_secondaryContainer = Color(0xFF7D2D18)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_tertiary = Color(0xFFE2C28C)
val md_theme_dark_onTertiary = Color(0xFF412D05)
val md_theme_dark_tertiaryContainer = Color(0xFF5A4319)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A16)
val md_theme_dark_onBackground = Color(0xFFEBE0D4)
val md_theme_dark_surface = Color(0xFF1E1A16)
val md_theme_dark_onSurface = Color(0xFFEBE0D4)
val md_theme_dark_surfaceVariant = Color(0xFF50463A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9E8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A16)
val md_theme_dark_inverseSurface = Color(0xFFEBE0D4)
val md_theme_dark_inversePrimary = Color(0xFF8F5600)
