name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Скрипт сам найдет, где лежит gradlew (в корне или в подпапке app), и сделает его исполняемым
    - name: Grant execute permission for gradlew
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
        elif [ -f "./app/gradlew" ]; then
          chmod +x ./app/gradlew
        fi
      
    # Запуск сборки в зависимости от того, где лежит файл
    - name: Build with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        elif [ -f "./app/gradlew" ]; then
          cd app && ./gradlew assembleDebug
        fi

    # Поиск готового APK и загрузка его в артефакты
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DojoStreak-APK
        path: "**/build/outputs/apk/debug/*.apk"
